//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MonthlyExpenseClaim
    {
        [ScaffoldColumn(false)]
        public int ID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
        public int CustomerID { get; set; }
        public int CustomerEmployeeID { get; set; }
        public int ExpenseItemID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string WBS { get; set; }
        [ScaffoldColumn(false)]
        public int StatusID { get; set; }

        public Nullable<bool> Approved {get;set;}
        [ScaffoldColumn(false)]
        public Nullable<int> CreatedBy { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> ModifiedBy { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerEmployee CustomerEmployee { get; set; }
        public virtual ExpenseItem ExpenseItem { get; set; }
        public virtual Status Status { get; set; }
    }
}
